version: "3"
services:
  app:
    image: db_vgames
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./provision/app/Dockerfile
    command: uvicorn core.main:app --host 0.0.0.0 --port 5000 --reload
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src

  db:
    restart: always
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videogames
    volumes:
      - db:/var/lib/postgresql/data
      - .:/usr/src
